# Generated by Django 2.1.2 on 2019-01-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_deidentify', '0002_auto_20181211_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procdocfile', models.FileField(upload_to='procdocuments')),
            ],
        ),
    ]
