# Generated by Django 2.1.2 on 2019-01-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_deidentify', '0003_procdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procdocument',
            name='procdocfile',
            field=models.FileField(upload_to='processed'),
        ),
    ]
