# Generated by Django 2.1.2 on 2019-01-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_deidentify', '0004_auto_20190117_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procdocument',
            name='procdocfile',
            field=models.FileField(upload_to='procdocuments'),
        ),
    ]
